### ISSUE TITLE
Friv controls thing doesn't work anymore

### ISSUE THREAD

**Issue by oriolazotroll52** [Tsyuay/FrivReborn#1]
It says: Movie not loaded...

**Comment by Tsyuay** [comment]
Try refreshing the page or did you put the swf in the game folder?

**Comment by Tsyuay** [comment]
If is still not loading i checked on you HTML and you need to replace var gn="minitrain"; with var gn="defend-your-nuts-12144"; and then when github pages is done building, refresh and then it will load.

**Comment by oriolazotroll52** [comment]
It only doesn't work on my version, your website also has this same problem

**Comment by oriolazotroll52** [comment]
[https://ibb.co/TttBMvX](url)

**Comment by Tsyuay** [comment]
if you want to leave to the main page but the lb doesn't load you can press the away key on the browser or try refreshing the page
 
![Screenshot_48](https://user-images.githubusercontent.com/83605971/120119880-71856e80-c170-11eb-9319-4afd9af86035.png)

**Comment by Tsyuay** [comment]
you can also refresh the page several times, copy and pasting the url and then close the old tab and pasting the url, or clearing cache

**Comment by Tsyuay** [comment]
@oriolazotroll52 is it working now? it was not working as it was requesting a wrong url and it don't loaded. but i hosted one and it now loads

**Comment by oriolazotroll52** [comment]
Yep, it's works now, thx for helping me!
