### ISSUE TITLE
this hapens when i try to play pipe to pipe

### ISSUE THREAD

**Issue by riegel2000** [Tsyuay/FrivReborn#2]
![Bildschirmfoto](https://user-images.githubusercontent.com/85353901/120813195-f5af6b80-c54d-11eb-907a-92806a133906.PNG)

**Comment by Tsyuay** [comment]
that's completely normal. some games also have the same issue but i don't know how to resize the game screen i know to change the screen size but not the game screen size

**Comment by Tsyuay** [comment]
oh @riegel2000 man! sorry if i delayed 16 days to solve your problem but it's averything fine now! sadly the progress as been reseted and screen is messed a little bit but the game is on the size it should be, it works now? i can later solve it fast as possible.

**Comment by Tsyuay** [comment]
Issue solved

**Comment by Tsyuay** [comment]
Issue closed
