### ISSUE TITLE
Hi Tsyuay

### ISSUE THREAD

**Issue by deividbinev12** [Tsyuay/FrivReborn#4]
i'm happy thanks for friv classic back but... what happened why there is 404 page why so fix friv classic please

We Want Late Night Games Back https://frivsecretos.blogspot.com/p/late-night-games.html?m=1 look please return

Thank You For Help Friv Classic

**Comment by Tsyuay** [comment]
Hello there, sadly it's not possible to restore the late night games, because it as been partially removed fron the 2020 menu.

**Comment by deividbinev12** [comment]
i know but download flash cs6 you don't know need help

install help 1. mission
https://youtu.be/kmSjP7bD8BA

flash cs6 website make 2. mission
https://youtu.be/Qn3mDxDqQ1o

you don't know flash cs6 that's flash player this is animation and games but Friv used Flash CS6 that's website menu

if ruffles working flash website

**Comment by deividbinev12** [comment]
Hello?

**Comment by Tsyuay** [comment]
Hello, sorry for the delay but actually, I had a while ago FL CS6 in my computer, so I used this version to give Friv Reborn life. So I checked the code in my actual .FLA of the menu I currently have and found some code that references Late, but they don't seem to function anymore
![16385011018871944506151751661415](https://user-images.githubusercontent.com/83605971/144538703-3f147c34-11b8-4223-9b0a-30b4e8baaaaa.jpg)
.
![16385009485741677199454301486120](https://user-images.githubusercontent.com/83605971/144538470-3c7e795a-e2a3-4923-8da0-7706829b0df3.jpg)

I mean, that moon doesn't appear.

**Comment by deividbinev12** [comment]
it's okay
