### ISSUE TITLE
Please add Sara's sweet cooking class

### ISSUE THREAD

**Issue by Frivclassic** [Tsyuay/FrivReborn#6]
Plz add Sara's sweet cooking class
It was my favorite game here is the red velvet cake game's[link.](Playsara.com/games/red-velvet/cake)
[Sara's baklava](Playsara.com/games/baklava)
[Peanut butter cookies](playsara.com/games/peanut-
butter-cookies)
Just click run anyway.
Tnx

**Comment by ClassicFriv** [comment]
Oops made a mistake that was my other account after I tested the links they don't work so here it is the link to
[Red velvet cake game.](http://playsara.com/games/red-velvet-cake)
[Baklava.](http://playsara.com/games/baklava)
[Black Forest Cake](http://playsara.com/games/black-forest-cake)
[Peanut butter cookies](http://playsara.com/games/peanut-butter-cookies)
Tnx.

**Comment by Tsyuay** [comment]
done
