### ISSUE TITLE
Missing Games

### ISSUE THREAD

**Issue by EricTheGamer7771** [Tsyuay/FrivReborn#75]
I was the one that asked for Sara's Sweet Cooking Class to be added here but I am on a different account.

Anyway I have some corrections on the game:

Red Velvet Cake: (Main Game)
The side menu is not supposed to say "Sara's Sweet Cooking Class" but just "Red Velvet Cake"

Baklava:
The side menu just simply says "Baklava"
http://www.playsara.com/games/baklava.swf

Black Forest Cake:
The side menu just says "Black Forest Cake"
http://www.playsara.com/games/black-forest-cake.swf

**Comment by HardPowerhtml** [comment]
Done!

**Comment by hhhjjjjj998** [comment]
https://7juegos.es/game_files/tagteamtitans/index.html
